name: Generate Snake

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.JungPrajal }}
          outputs: dist/output/github-snake.svg

      - name: Upload the animation
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/output/github-snake.svg

      - name: Push to the GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/output
